// Code generated by binclude; DO NOT EDIT.

package main

import (
	"github.com/lu4p/binclude"
	"time"
)

var (
	_binclude0	= []byte{102,105,108,101,46,116,120,116}
	_binclude1	= []byte{97,115,115,101,116,49}
	_binclude2	= []byte{97,115,115,101,116,49}
	_binclude3	= []byte{115,117,98,100,105,114,97,115,115,101,116,49}
	_binclude4	= []byte{115,117,98,100,105,114,97,115,115,101,116,49}
)
var binFS = binclude.FileSystem{"file.txt": {Filename: "file.txt", Mode: 420, ModTime: time.Unix(1592104011, 0), Content: _binclude0}, "assets": {Filename: "assets", Mode: 2147484141, ModTime: time.Unix(1592147369, 0), Content: nil}, "assets/asset1.txt": {Filename: "asset1.txt", Mode: 420, ModTime: time.Unix(1592103949, 0), Content: _binclude1}, "assets/asset2.txt": {Filename: "asset2.txt", Mode: 420, ModTime: time.Unix(1592103958, 0), Content: _binclude2}, "assets/subdir": {Filename: "subdir", Mode: 2147484141, ModTime: time.Unix(1592104033, 0), Content: nil}, "assets/subdir/subdirasset1.txt": {Filename: "subdirasset1.txt", Mode: 420, ModTime: time.Unix(1592104027, 0), Content: _binclude3}, "assets/subdir/subdirasset2.txt": {Filename: "subdirasset2.txt", Mode: 420, ModTime: time.Unix(1592104033, 0), Content: _binclude4}}
