// Code generated by binclude; DO NOT EDIT.

package example

import (
	"github.com/lu4p/binclude"
	"time"
)

var (
	_binclude0 = []byte("subdirasset1")
	_binclude1 = []byte("subdirasset1")
	_binclude2 = []byte("file.txt")
	_binclude3 = []byte("asset1")
	_binclude4 = []byte("asset1")
	BinFS      = binclude.FileSystem{"assets/subdir/subdirasset1.txt": {Filename: "subdirasset1.txt", Mode: 420, ModTime: time.Unix(1592104027, 0), Content: _binclude0}, "assets/subdir/subdirasset2.txt": {Filename: "subdirasset2.txt", Mode: 420, ModTime: time.Unix(1592104033, 0), Content: _binclude1}, "file.txt": {Filename: "file.txt", Mode: 420, ModTime: time.Unix(1592104011, 0), Content: _binclude2}, "assets": {Filename: "assets", Mode: 2147484141, ModTime: time.Unix(1592518785, 0), Content: nil}, "assets/asset1.txt": {Filename: "asset1.txt", Mode: 420, ModTime: time.Unix(1592103949, 0), Content: _binclude3}, "assets/asset2.txt": {Filename: "asset2.txt", Mode: 420, ModTime: time.Unix(1592103958, 0), Content: _binclude4}, "assets/subdir": {Filename: "subdir", Mode: 2147484141, ModTime: time.Unix(1592104033, 0), Content: nil}}
)
